# Screen dimensions
WIDTH, HEIGHT = 1080, 720

# Boid settings
NUM_BOIDS = 100
MAX_SPEED = 3
NEIGHBOR_RADIUS = 80
SEPARATION_RADIUS = 30

# Sliders for adjusting weights
ALIGNMENT_WEIGHT = 0.05
COHESION_WEIGHT = 0.005
SEPARATION_WEIGHT = 0.05

